---
language: java

jdk:
  - oraclejdk8

env:
  global:
    - KUBECONFIG=${HOME}/.kube/kubernaut_shim

install:
  - pip3 install kubernaut_shim
  - kubernaut_shim set-token ${KUBERNAUT_TOKEN}

before_script:
  - kubernaut_shim claim

after_script:
  - kubernaut_shim discard

script:
  - echo "Remove this and the next line and add your CI build and test logic here"
  - javac -version
