#!/usr/bin/env sh

PROGRAM="$(basename $0)"
IMAGE="datawire/kubernaut"
VERSION="latest"

error() {
  error_code=$1
  echo "ERROR: $2" >&2
  echo "($PROGRAM wrapper version: $VERSION, error code: $error_code )" &>2
  exit $1
}

check_cmd_in_path() {
  cmd=$1
  which $cmd > /dev/null 2>&1 || error 1 "'$cmd' not found on \$PATH!"
}

check_cmd_in_path docker

# Set up mounted volumes, environment, and run our containerized command
exec docker run \
  --interactive \
  --tty \
  --rm \
  --volume "${HOME}/.config/kubernaut":/home/kubernaut/.config/kubernaut \
  --workdir /work \
  "$IMAGE:$VERSION" "$@"